exclude: [README.md, bower.json, composer.json, package.json]

# Dependencies
markdown:   kramdown
pygments:   true

# Permalinks
permalink:        pretty

cdn_css:          //netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css
cdn_theme_css:    //netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css
cdn_js:           //netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js
